apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  annotations:
    approved: "true" # Is service approved by devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - name: example-service
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: 512Mi
          requests:
            cpu: "25m"
            memory: 256Mi